language: cpp
script: ./build

# Force use modern cpp environment, see http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7