#!/bin/sh

# Assume script resides inside the project root directory and is always called from there
if [ "$CPPCHECK" = "RUN" ]
then
  cppcheck --enable=all -i tests --error-exitcode=1 ./src/
else
  ./build && cd ./src/lexer/tests/ && ./tests.sh
fi
