#!/bin/sh

# get path of this script file
BASEDIR=$(dirname "$(readlink -f "$0")")

(./build_debug)
ret=$?
if [ $ret -ne 0 ]; then
  exit 1
fi

(${BASEDIR}/tests/lexer/tests.sh)
ret=$?
if [ $ret -ne 0 ]; then
  exit 1
fi

(MJ_RUN="${BASEDIR}/run" ${BASEDIR}/tests/mjtest/mjt.py --parallel --produce_no_reports all)
ret=$?
if [ $ret -ne 0 ]; then
  exit 1
fi

exit 0
