#!/bin/sh

# get path of this script file
BASEDIR=$(dirname "$(readlink -f "$0")")

# run cmake
(cd "${BASEDIR}" && cmake "${BASEDIR}" -DCMAKE_BUILD_TYPE=Debug)
ret=$?
if [ $ret -ne 0 ]; then
  exit 1
fi

# run make
(cd "${BASEDIR}" && make -j 4 -C "${BASEDIR}")
ret=$?
if [ $ret -ne 0 ]; then
  exit 1
fi

exit 0
